sudo: required
services:
  - docker

before_install:
  - docker build -t gladyshav/docker-react -f Dockerfile.dev .

script:
  - docker run gladyshav/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-us-east-2-007472637022"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
  # app: "docker" - name of project
  # Docker-env.nq4ttky5u9.us-east-2.elasticbeanstalk.com